### ISSUE TITLE
End User Test

### ISSUE THREAD

**Issue by mmhxv3** [mmhxv3/4320Group18#10]
We need to allow an "end user" (someone who is not us) to test the system so that we can get an insight as to possible issues and bugs that may arise. Following that we will be able to create more issues that may be discovered upon testing.

**Comment by mmhxv3** [comment]
End User #1 Feedback

Good things:
- Repo openness seems like a useful thing to measure
- Likes the top authors by commit as opposed to lines of code.

Things to improve:
- Days until repo is archived is hard to understand and needs to be reworked
- Could be more visually appealing
- Graphs are kind of hard to read

**Comment by Whatever23333** [comment]
Thanks for his comment, hope we have more end users' feedback. We will still keep this issue open.

**Comment by ElBureeto** [comment]
End User Test #2
Good Things:
--Archive is much easier to understand
--Likes that we have a specific tab for group project

Things to improve:
--Fix bug with Top Authors
--Make graph more readable
