### ISSUE TITLE
Improve UI on Group 18 page

### ISSUE THREAD

**Issue by mmhxv3** [mmhxv3/4320Group18#3]
The styling on our page could be improved, especially as regards the days until archived feature. Could create a new component with more style and functionality (color changing according to active, inactive, etc.)

**Comment by sgoggins** [comment]
be more specific.

**Comment by Whatever23333** [comment]
The styling on our page could be improved, especially as regards the days until archived feature.
1. For merging rate of a project. We can show a chart with the number of number of total pull requests and the merged pull requests. And according to the rate, we show an 'openness' in different colors.(Green  for >= 75%, Yellow for 50% - 75%, Red for under 50%)
2. For Active status of a project. We show the status in Green(if it is active) or Red(if it is inactive), then note the last edit date for the projects.
3. For the top contributors. We will make a list of top contributors and for the first place, we will user larger font and a golden bolder for the first place, silver for the second place, and bronze for the third

**Comment by ElBureeto** [comment]
Added color coding to archive status.

**Comment by Whatever23333** [comment]
Cool work!

**Comment by ElBureeto** [comment]
Top Contributors leader board implemented
