### ISSUE TITLE
Create developer-instructions.md

### ISSUE THREAD

**Issue by mmhxv3** [mmhxv3/4320Group18#6]
We need documentation as to how we got the app running on an EC2 instance (how to get augur on the server, how to create the necessary python venv, how to get the app to continue running even after the SSH user logs out, etc.)

**Comment by Whatever23333** [comment]
We can add more contents in the documentation. We can list all the new functions we created our project. We can list all the work we have done on it based on a timeline as well.

**Comment by Whatever23333** [comment]
Documentation uploaded, looks good.
